#+TITLE: Attachment Converter
#+AUTHOR: Matt Teichman
#+DESCRIPTION: Command-line utility for batch-converting attachments in an email mailbox
#+OPTIONS: toc:nil, num:nil

* For Outside Users

Attachment Converter is in alpha.  If you'd like to try it out, please
follow the instructions on [[https://dldc.lib.uchicago.edu/open/attachment-converter][our project website]].

* For UChicago Library Developers

Welcome on board the =attachment-converter= project!

** Guides for Developers

The guides on our development workflow break down into two main
documents:

+ [[doc/new-features.md][adding new features]]
+ [[doc/sandboxing.md][using sandboxed switches]]

** Current State of the Project

We have ambitions to make Attachment Converter follow
library-executable design.  Although it can be installed as a library,
for the first release, we are focusing on its executable
functionality.

The following features are presently working:

+ Attachment Converter can be used with one of two email parsing
  backends: [[http://projects.camlcity.org/projects/ocamlnet.html][OCamlnet]] or [[https://github.com/mirage/mrmime][Mr. Mime]].  (This is not yet configurable but
  it will be soon---right now, you have to change the email parsing
  backend by changing one line of the source code.)
+ Attachment Converter will print out a "skeleton" of the email it is
  converting, showing the user the before and after structure.
+ By default, Attachment Converter converts:
  - PDF
  - DOC
  - DOCX
  - XLS
  - XLSX
  - JPG
  - GIF
+ Attachment Converter follows Unix filter design, accepting standard
  in and outputting to standard out.
+ Attachment Converter allows the user to configure the external
  utilities it calls out to to perform the relevant conversions in its
  configuration file.

** Current Team

Our illustrious team of developers currently includes:

+ [[https://elucidations.vercel.app/][Matt Teichman]]
+ [[https://github.com/nmmull][Nathan Mull]]
+ [[https://www.lib.uchicago.edu/about/directory/staff/emily-schartz/][Emily Schartz]]
+ [[https://www.linkedin.com/in/mattjackson23/][Matt Jackson]]

Previous developers include:

+ [[https://github.com/OwenPriceSkelly][Owen Price Skelly]]
+ [[https://github.com/cormacd9818][Cormac Duhamel]]
+ [[https://www.linkedin.com/in/nk45/][Nishchay Karle]]
+ [[https://theworldofobi.github.io/][Obi Obetta]]

[[https://elucidations.vercel.app/][Matt Teichman]], [[https://github.com/nmmull][Nathan Mull]], [[https://www.lib.uchicago.edu/about/directory/staff/emily-schartz/][Emily Schartz]], and [[https://www2.lib.uchicago.edu/keith/][Keith Waclena]] will be
contributing to and maintaining the project on an longterm basis.
Matt is currently in charge of managing the project.

* Background on the email format
    
** Reading

Here is a link to the RFC-s that define the email specification. These
are shamelessly pilfered from the impressive [[https://github.com/mirage/mrmime][Mr. Mime]] GitHub README:

+ https://datatracker.ietf.org/doc/html/rfc822
+ https://datatracker.ietf.org/doc/html/rfc2822
+ https://datatracker.ietf.org/doc/html/rfc5321
+ https://datatracker.ietf.org/doc/html/rfc5322
+ https://datatracker.ietf.org/doc/html/rfc2045
+ https://datatracker.ietf.org/doc/html/rfc2046
+ https://datatracker.ietf.org/doc/html/rfc2047
+ https://datatracker.ietf.org/doc/html/rfc2049
+ https://datatracker.ietf.org/doc/html/rfc6532

** Viewing

Romain Calascibetta's overview talk from [[https://icfp16.sigplan.org/program/program-icfp-2016/][ICFP 2016]] is truly excellent
and recommended to all.  You never knew email addresses could be so
complicated.

https://www.youtube.com/watch?v=kQkRsNEo25k
